#!/bin/bash

# ============================================================
# Network Security Scan Report Generator
# ============================================================

write_header() {
    local target="$1"
    echo "============================================================"
    echo "           NETWORK SECURITY SCAN REPORT                    "
    echo "============================================================"
    echo ""
    echo "  Target IP Address / Hostname:  $target"
    echo "  Scan Date / Time:              $(date '+%Y-%m-%d %H:%M:%S')"
    echo "  Report Generated By:           Network Scanner v2.5"
    echo ""
    echo "------------------------------------------------------------"
}

write_ports_section() {
    local target="$1"

    echo ""
    echo "  [1]  OPEN PORTS AND DETECTED SERVICES"
    echo "  ----------------------------------------"
    echo ""

    nmap -sV "$target" | grep "open"

    echo ""
    echo "------------------------------------------------------------"
}

write_vulns_section() {
    local target="$1"

    echo ""
    echo "  [2]  POTENTIAL VULNERABILITIES IDENTIFIED"
    echo "  ----------------------------------------"
    echo ""

    # Run the enhanced NSE vuln scan once and capture the full output.
    # This is the same expensive scan reused by both strategies below.
    local SCAN_RESULTS
    SCAN_RESULTS=$(nmap -sV --script vuln "$target")

    # ---- Strategy A: Grep for high-confidence NSE results ----
    echo "  --- High-Confidence NSE Findings (keyword: VULNERABLE) ---"
    echo ""

    local grep_hits
    grep_hits=$(echo "$SCAN_RESULTS" | grep "VULNERABLE")

    if [ -n "$grep_hits" ]; then
        echo "$grep_hits"
    else
        echo "    No lines containing 'VULNERABLE' were found by NSE scripts."
    fi

    echo ""
    echo "  --- Analyzing Service Versions (custom checks) ---"
    echo ""

    # ---- Strategy B: case-statement version checks ----
    local version_hits
    version_hits=$(echo "$SCAN_RESULTS" | while read -r line; do
        case "$line" in
            *"vsftpd 2.3.4"*)
                echo "    [!!] VULNERABILITY DETECTED: vsftpd 2.3.4 is running, which contains a known critical backdoor."
                ;;
            *"Apache httpd 2.4.49"*)
                echo "    [!!] VULNERABILITY DETECTED: Apache 2.4.49 is running, which is vulnerable to path traversal (CVE-2021-41773)."
                ;;
            *"OpenSSH 7.2"*)
                echo "    [!!] VULNERABILITY DETECTED: OpenSSH 7.2 is running, which is affected by a username enumeration vulnerability (CVE-2016-6210)."
                ;;
            *"ProFTPD 1.3.3"*)
                echo "    [!!] VULNERABILITY DETECTED: ProFTPD 1.3.3 is running, which contains a backdoor vulnerability (CVE-2010-4221)."
                ;;
        esac
    done)

    if [ -n "$version_hits" ]; then
        echo "$version_hits"
    else
        echo "    No known-vulnerable service versions matched the custom checks."
    fi

    echo ""
    echo "------------------------------------------------------------"
}

write_recs_section() {
    echo ""
    echo "  [3]  RECOMMENDATIONS FOR REMEDIATION"
    echo "  ----------------------------------------"
    echo ""
    echo "    1.  Update all software and services to their latest stable versions."
    echo ""
    echo "    2.  Change all default credentials immediately, especially on FTP"
    echo "        and any admin interfaces."
    echo ""
    echo "    3.  Disable weak SSL/TLS cipher suites; enforce TLS 1.2 or higher."
    echo ""
    echo "    4.  Implement a firewall and restrict open ports to only those"
    echo "        required for business operations."
    echo ""
    echo "    5.  Schedule regular vulnerability scans and patch management reviews."
    echo ""
    echo "------------------------------------------------------------"
}

write_footer() {
    echo ""
    echo "  END OF REPORT"
    echo "  Generated on: $(date '+%A, %B %d, %Y at %H:%M:%S %Z')"
    echo ""
    echo "============================================================"
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <target_ip_or_hostname>" >&2
        exit 1
    fi

    local target="$1"
    local REPORT_FILE="report.txt"

    write_header "$target"        > "$REPORT_FILE"
    write_ports_section "$target" >> "$REPORT_FILE"
    write_vulns_section "$target" >> "$REPORT_FILE"
    write_recs_section      >> "$REPORT_FILE"
    write_footer            >> "$REPORT_FILE"

    echo "Report successfully written to: $REPORT_FILE"
}

main "$@"
