#!/bin/bash

# ============================================================
# Network Security Scan Report Generator
# ============================================================

write_header() {
    local target="$1"
    echo "============================================================"
    echo "           NETWORK SECURITY SCAN REPORT                    "
    echo "============================================================"
    echo ""
    echo "  Target IP Address / Hostname:  $target"
    echo "  Scan Date / Time:              $(date '+%Y-%m-%d %H:%M:%S')"
    echo "  Report Generated By:           Network Scanner v1.0"
    echo ""
    echo "------------------------------------------------------------"
}

write_ports_section() {
    local target="$1"

    echo ""
    echo "  [1]  OPEN PORTS AND DETECTED SERVICES"
    echo "  ----------------------------------------"
    echo ""

    nmap -sV "$target" | grep "open"

    echo ""
    echo "------------------------------------------------------------"
}

write_vulns_section() {
    echo ""
    echo "  [2]  POTENTIAL VULNERABILITIES IDENTIFIED"
    echo "  ----------------------------------------"
    echo ""
    echo "    ID / NAME                   DESCRIPTION"
    echo "    -------------------------   ----------------------------------------"
    echo "    CVE-2023-XXXX               Outdated Web Server - Apache version"
    echo "                                exposed to known remote exploits."
    echo ""
    echo "    CVE-2022-YYYY               SSL/TLS Misconfiguration - Weak cipher"
    echo "                                suites detected on port 443."
    echo ""
    echo "    Default Credentials         FTP Server on port 21 appears to accept"
    echo "                                default username/password combinations."
    echo ""
    echo "------------------------------------------------------------"
}

write_recs_section() {
    echo ""
    echo "  [3]  RECOMMENDATIONS FOR REMEDIATION"
    echo "  ----------------------------------------"
    echo ""
    echo "    1.  Update all software and services to their latest stable versions."
    echo ""
    echo "    2.  Change all default credentials immediately, especially on FTP"
    echo "        and any admin interfaces."
    echo ""
    echo "    3.  Disable weak SSL/TLS cipher suites; enforce TLS 1.2 or higher."
    echo ""
    echo "    4.  Implement a firewall and restrict open ports to only those"
    echo "        required for business operations."
    echo ""
    echo "    5.  Schedule regular vulnerability scans and patch management reviews."
    echo ""
    echo "------------------------------------------------------------"
}

write_footer() {
    echo ""
    echo "  END OF REPORT"
    echo "  Generated on: $(date '+%A, %B %d, %Y at %H:%M:%S %Z')"
    echo ""
    echo "============================================================"
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <target_ip_or_hostname>" >&2
        exit 1
    fi

    local target="$1"
    local REPORT_FILE="report.txt"

    write_header "$target"        > "$REPORT_FILE"
    write_ports_section "$target" >> "$REPORT_FILE"
    write_vulns_section     >> "$REPORT_FILE"
    write_recs_section      >> "$REPORT_FILE"
    write_footer            >> "$REPORT_FILE"

    echo "Report successfully written to: $REPORT_FILE"
}

main "$@"
