#!/bin/bash

# ============================================================
# Network Security Scan Report Generator
# ============================================================

write_header() {
    local target="$1"
    echo "============================================================"
    echo "           NETWORK SECURITY SCAN REPORT                    "
    echo "============================================================"
    echo ""
    echo "  Target IP Address / Hostname:  $target"
    echo "  Scan Date / Time:              $(date '+%Y-%m-%d %H:%M:%S')"
    echo "  Report Generated By:           Network Scanner v1.0"
    echo ""
    echo "------------------------------------------------------------"
}

write_ports_section() {
    local target="$1"

    echo ""
    echo "  [1]  OPEN PORTS AND DETECTED SERVICES"
    echo "  ----------------------------------------"
    echo ""

    nmap -sV "$target" | grep "open"

    echo ""
    echo "------------------------------------------------------------"
}

# query_nvd "product_name" "product_version"
# Queries the NVD REST API for known CVEs matching a product/version
# keyword search and prints a formatted summary (CVE ID, description,
# severity) suitable for appending straight into the report.
query_nvd() {
    local product="$1"
    local version="$2"
    # The NVD API is public but has rate limits. We'll request a small number of results.
    local results_limit=3

    echo # Add a newline for formatting
    echo "Querying NVD for vulnerabilities in: $product $version..."

    # The API needs a URL-encoded string. A simple space-to-%20 works for many cases.
    local search_query
    search_query=$(echo "$product $version" | sed 's/ /%20/g')

    local nvd_api_url="https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=${search_query}&resultsPerPage=${results_limit}"

    # Use curl to fetch the data (-s for silent) and jq to parse the JSON response.
    local vulnerabilities_json
    vulnerabilities_json=$(curl -s "$nvd_api_url")

    # --- Defensive Programming: Check for Errors ---
    if [[ -z "$vulnerabilities_json" ]]; then
        echo "  [!] Error: Failed to fetch data from NVD. The API might be down or unreachable."
        return
    fi
    if echo "$vulnerabilities_json" | jq -e '.message' > /dev/null 2>&1; then
        echo "  [!] NVD API Error: $(echo "$vulnerabilities_json" | jq -r '.message')"
        return
    fi
    if ! echo "$vulnerabilities_json" | jq -e '.vulnerabilities[0]' > /dev/null 2>&1; then
        echo "  [+] No vulnerabilities found in NVD for this keyword search."
        return
    fi
    # --- End Error Checks ---

    # This jq command filters the JSON and formats it for our report.
    # It extracts the CVE ID, the English description, and the severity.
    echo "$vulnerabilities_json" | jq -r \
        '.vulnerabilities[] |
        "  CVE ID: \(.cve.id)\n  Description: \((.cve.descriptions[] | select(.lang=="en")).value | gsub("\n"; " "))\n  Severity: \(.cve.metrics.cvssMetricV31[0].cvssData.baseSeverity // .cve.metrics.cvssMetricV2[0].cvssData.baseSeverity // "N/A")\n---"'
}

write_vulns_section() {
    local target="$1"

    echo ""
    echo "  [2]  POTENTIAL VULNERABILITIES IDENTIFIED"
    echo "  ----------------------------------------"
    echo ""

    # Run the enhanced NSE vuln scan once and capture the full output.
    # This is the same expensive scan reused by both strategies below.
    local SCAN_RESULTS
    SCAN_RESULTS=$(nmap -sV --script vuln "$target")

    # ---- Strategy A: Grep for high-confidence NSE results ----
    echo "  --- High-Confidence NSE Findings (keyword: VULNERABLE) ---"
    echo ""

    local grep_hits
    grep_hits=$(echo "$SCAN_RESULTS" | grep "VULNERABLE")

    if [ -n "$grep_hits" ]; then
        echo "$grep_hits"
    else
        echo "    No lines containing 'VULNERABLE' were found by NSE scripts."
    fi

    echo ""
    echo "  --- Analyzing Service Versions (custom checks + live NVD lookups) ---"
    echo ""

    # Cap how many live NVD queries we make per scan. Keep this at 1-2 while
    # testing/developing so you don't get temporarily rate-limited by the
    # public API; raise it once you're confident things work reliably.
    local MAX_NVD_QUERIES=2
    local NVD_QUERY_COUNT=0

    # ---- Strategy B: case-statement version checks + NVD lookups ----
    echo "$SCAN_RESULTS" | while read -r line; do
        local product=""
        local version=""

        # Extract a clean "product" and "version" pair from lines we recognize.
        # Each case also prints our own quick-hit warning (as before), then
        # falls through to a live NVD query for that specific product/version.
        case "$line" in
            *"vsftpd 2.3.4"*)
                echo "    [!!] VULNERABILITY DETECTED: vsftpd 2.3.4 is running, which contains a known critical backdoor."
                product="vsftpd"
                version="2.3.4"
                ;;
            *"Apache httpd 2.4.49"*)
                echo "    [!!] VULNERABILITY DETECTED: Apache 2.4.49 is running, which is vulnerable to path traversal (CVE-2021-41773)."
                product="Apache httpd"
                version="2.4.49"
                ;;
            *"OpenSSH 7.2"*)
                echo "    [!!] VULNERABILITY DETECTED: OpenSSH 7.2 is running, which is affected by a username enumeration vulnerability (CVE-2016-6210)."
                product="OpenSSH"
                if [[ "$line" =~ OpenSSH\ ([0-9.]+[a-zA-Z0-9]*) ]]; then
                    version="${BASH_REMATCH[1]}"
                fi
                ;;
            *"ProFTPD 1.3.3"*)
                echo "    [!!] VULNERABILITY DETECTED: ProFTPD 1.3.3 is running, which contains a backdoor vulnerability (CVE-2010-4221)."
                product="ProFTPD"
                version="1.3.3"
                ;;
        esac

        # Only query NVD when we actually captured a product/version pair,
        # and cap the number of live lookups per scan to stay within the
        # NVD public API's rate limits (raise MAX_NVD_QUERIES once you've
        # confirmed things work reliably).
        if [[ -n "$product" && -n "$version" ]]; then
            if [[ "$NVD_QUERY_COUNT" -lt "$MAX_NVD_QUERIES" ]]; then
                query_nvd "$product" "$version"
                NVD_QUERY_COUNT=$((NVD_QUERY_COUNT + 1))
            else
                echo "    [i] Skipping NVD lookup for $product $version (rate-limit cap of $MAX_NVD_QUERIES reached)."
            fi
        fi
    done

    if ! echo "$SCAN_RESULTS" | grep -qE "vsftpd 2\.3\.4|Apache httpd 2\.4\.49|OpenSSH 7\.2|ProFTPD 1\.3\.3"; then
        echo "    No known-vulnerable service versions matched the custom checks."
    fi

    echo ""
    echo "------------------------------------------------------------"
}

write_recs_section() {
    echo ""
    echo "  [3]  RECOMMENDATIONS FOR REMEDIATION"
    echo "  ----------------------------------------"
    echo ""
    echo "    1.  Update all software and services to their latest stable versions."
    echo ""
    echo "    2.  Change all default credentials immediately, especially on FTP"
    echo "        and any admin interfaces."
    echo ""
    echo "    3.  Disable weak SSL/TLS cipher suites; enforce TLS 1.2 or higher."
    echo ""
    echo "    4.  Implement a firewall and restrict open ports to only those"
    echo "        required for business operations."
    echo ""
    echo "    5.  Schedule regular vulnerability scans and patch management reviews."
    echo ""
    echo "------------------------------------------------------------"
}

write_footer() {
    echo ""
    echo "  END OF REPORT"
    echo "  Generated on: $(date '+%A, %B %d, %Y at %H:%M:%S %Z')"
    echo ""
    echo "============================================================"
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <target_ip_or_hostname>" >&2
        exit 1
    fi

    local target="$1"
    local REPORT_FILE="report.txt"

    write_header "$target"        > "$REPORT_FILE"
    write_ports_section "$target" >> "$REPORT_FILE"
    write_vulns_section "$target" >> "$REPORT_FILE"
    write_recs_section      >> "$REPORT_FILE"
    write_footer            >> "$REPORT_FILE"

    echo "Report successfully written to: $REPORT_FILE"
}

main "$@"
